# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'api_practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for api_practice
 pod 'Toast-Swift', '~> 5.0.1'
 pod 'Alamofire','~> 5.2'
 pod 'SwiftyJSON'
end
